### ISSUE TITLE
Accessing MolecularData data and generating one-body integrals

### ISSUE THREAD

**Issue by TariniHardikar** [ProjectQ-Framework/FermiLib-Plugin-Psi4#18]
Hi!

I had a few questions on how MolecularData accesses information and how onebody integrals are constructed. 

1. How is `molecule.one_body_integrals` constructed? Is this from PSI4 or independent of it? I believe these integrals are in MO (since ao_kinetic+ao_potential != molecule.one_body_integrals), but PSI4 normally doesn't keep track of molecular orbital information, so where does this array come from?

2. When `molecular.one_body_integrals` is already in the MO basis, why does the template file convert the AO orbitals from PSI4 and transform them to the MO, only to set it equal to 
```
molecule.one_body_integrals = one_body_basis_change(
            numpy.asarray(mints.ao_kinetic()), molecule.canonical_orbitals)
        molecule.one_body_integrals += one_body_basis_change(
numpy.asarray(mints.ao_potential()), molecule.canonical_orbitals) 
```
3. Finally, how does the plugin read the information generated by PSI4 (ie, how are the attributes of MolecularData objects filled)?

Sorry for bothering you with so many questions, I really appreciate any help!

Thanks!

**Comment by babbush** [comment]
Hi Tarini,

The first thing I'd like to mention is that most of the developers have actually forked FermiLib and are now actively developing a different package, OpenFermion (www.openfermion.org). OpenFermion is basically FermiLib but with the dependancies on ProjectQ removed from the core library and put into a plugin so that other frameworks made by other companies can use OpenFermion. We have also been adding new features to OpenFermion that won't be in FermiLib and will continue to do so. We will have a paper and announcement about this in two weeks.

1) Yes, the integrals come from running psi4. You can see what we're doing around line 88-91 of the template file (https://github.com/ProjectQ-Framework/FermiLib-Plugin-Psi4/blob/develop/fermilibpluginpsi4/_psi4_template). You are correct that Psi4 tends to keep the atomic, not molecular orbitals, so we perform a basis change on the one_body_integrals matrix to convert from AO to MO basis. We store only the MOs in FermiLib/OpenFermion.

2) I am a little confused by the question. This code is exactly where we are storing the one_body_integrals. This is the first time we generate these exact integrals. Note that what is happening in this line is that we are rotating the atomic orbital integrals to the canonical orbital integrals.

3) The class MolecularData is a FermiLib data structure. Psi4 runs that template file which performs Psi4 calculations which are then stored in the MolecularData class. After the Psi4 calculation, the MolecularData class is saved with aspects from the Psi4 calculation populated. Does this make sense?

**Comment by TariniHardikar** [comment]
Hi Ryan,

Thank you! I understand what's happening now.

I'll definitely check out OpenFermion as well.
