### ISSUE TITLE
Assigning charges to atoms  

### ISSUE THREAD

**Issue by TariniHardikar** [ProjectQ-Framework/FermiLib-Plugin-Psi4#19]
Hi!

First, I think this question also applies to OpenFermion, given that the plugins have very similar structure. This might be a very trivial question, but how are charges assigned to atoms for a given molecule?

For instance, for the molecule is `Li_2` with `charge = 2`. Then, I'm guessing each lithium atom gets one positive charge, right? What if I want to specify that one lithium atom has charge +2, while the other is a neutral atom? Is that possible? If I have a chain of say 5 lithium atoms, and set my total charge to +5, does each atom get a +1 charge?

For molecules with atoms with large electronegativity difference, I'm sure it is straightforward, but what about molecules like the ones described here?

Thanks!

**Comment by babbush** [comment]
Hi Tarini,

The Li nuclei have a certain positive charge based on where they are on the periodic table. All Li atoms are a +3 charge. When you set the charge for a molecule, e.g. charge = 2, you are really specifying how many electrons are in the system (in this case 4 instead of 6). So it is not really valid to try to set charges on particular nuclei, only on the entire system. I will close this issue, hope it helps.
